version: '3'
services:
  service:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: python:3.9-buster
    working_dir: /app
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 1010 --reload --log-level debug --use-colors
    environment:
    - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    ports:
      - 1010:1010
    